### PR TITLE
#315 loosen system.web

### PR DESCRIPTION
**Pull request by Worthaboutapig**
I've implemented moving HttpUtility into an interface to show the approach.  I tried a number of things, and this seems to have the least impact on the existing code-base.
Created projects for Asp.Net and Nancy to show how to use it.  Future users would need to update the `SquishIt.Configuration` for `SquishIt.AspNet.Configuration` in order to get the right web dependencies configured.  As there is this `Configuration`, used statically, it wasn't easy to abstract out and this was the neatest way I found.

I created a private class within `MachineConfigReader` to handle the `System.Web.Configuration.DeploymentSection`, as that would have to be done for every web framework except ASP.NET, so it's a lot simpler to do it for all and avoid the interface.
Similarly one or more enumerations will have to be copied internally to SquishIt for similar reasons (e.g. 
`AspNetHostingPermissionLevel`).

Please take a look and let me know what you think.  I can implement the rest of the interfaces quickly, as I already prototyped them (mainly HttpContext, HttpRuntime)

I've done my best to follow the coding style, though it doesn't seem to be consistent ;)

### CODE REVIEW

**Comment by AlexCuse** [comment]
Hey I just wanted to circle back and see where things stand on this - if you are done I can probably merge it manually into my branch and go from there.  Or if you're out of time, just let me know where you left off.

I could have sworn I replied to this before it must have gotten eaten.  Sorry about that.  And for the inconsistent code style - your stuff looks fine.  Some of the stuff that looks different is reaaaaaaaallllllllly old.

**Comment by Worthaboutapig** [comment]
Hi, sorry, I did get your previous message and I haven’t had a chance to look at it again yet and finish it off, but I should be able to by next week, if that’s ok.

Do you have a preference on the style?  Generally I go with R#...

**Comment by AlexCuse** [comment]
For styling, pretty much everything is VS / R# defaults (unless it wasn't at the time I got involved).

If you look at RelativePathAdapter, that is a pretty recent addition and should serve as an example.

Maybe as part of 1.0 release I'll try a global R# cleanup - last time I tried it didn't work so well but that was a few versions ago.

**Comment by AlexCuse** [comment]
Just realized I didn't answer your main question - next week is fine.  

Thanks again for this - we get Nancy questions a few times a year and I never really know how to answer them.

**Comment by AlexCuse** [comment]
What is the status on this?  I'd like to get 1.0 out soon.  Have some bandwidth at the moment if you need help.

**Comment by Worthaboutapig** [comment]
Hi, sorry I haven't looked at this, been a bit snowed under.  I'll try and take a look at it again today, feel free to pester me.

**Comment by Worthaboutapig** [comment]
Also, I can't quite see why, but when I run the tests in feature/v1.0, several blow up with

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidProgramException : Common Language Runtime detected an invalid program.
```

which is thrown as part of `Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues)`.  If I change tests to run under `x86` everything's fine, though this library is MSIL.  Any ideas? (I'm using the R# test runner and changing the Options->Platform in the test runner.

**Comment by AlexCuse** [comment]
I use testdriven.net haven't had any problems - it might be a testrunner issue.  Jurassic is squirelly in general though, I had almost as many issues with it in the past as I did with ironruby.  I wouldn't think you're changing a lot in the preprocessors (at least I hope) so don't worry about it too much.  

Just realized a new version of jurassic is out too, I will upgrade that today.  Let me know if you need a hand with anything - I'm hoping to get 1.0 out ASAP.

**Comment by Worthaboutapig** [comment]
Thanks, no, not expecting to touch the preproccessors themselves, just where the dependencies need extracting from the tests.  I can set R# to run in x86 mode for tests, which doesn't affect the commits, so it's likely an Jurassic/ R# incompatibility.

I'm working through the rest of it now, I'll make a pull request when I'm done, hopefully I can finish it off today.

Oh, do you have any view on Contracts (System.Contracts)? I use them rather than custom null-guards...

**Comment by AlexCuse** [comment]
Looks nice enough.  What is the experience like for external callers, that would be my main concern in any kind of change like that.

**Comment by Worthaboutapig** [comment]
I've got most of the work done, however, it's quite difficult pulling out the call site references, as there's a general static approach in the design.  Personally I'm not a fan of the service-locator Configuration.Instance approach, it makes this kind of refactoring awkward :)

I need to get fix a few more of the tests and abstract the caching.  Hopefully I can send a pull request tomorrow.

As for the Code Contracts, probably that won't be relevant as too much of the code expects injected references to be null, so adding guards doesn't work.

**Comment by AlexCuse** [comment]
Yeah I've come to terms with it over the years but there are definitely some frustrating things I run into now and then.  I'd like to replace the configuration stuff but don't really have a great idea on what to replace it with - that was all added slowly and it got unwieldy over time.  You're probably feeling more pain than anyone other than me has with that stuff right now, so if you have ideas I'd **love** to hear them.  I figure with 1.0 I can break whatever I want :)

Would love to introduce proper dependency injection but its more work than I have time for right now, and I'm not sure how much payoff there really is for the end user.  Once 1.0 is out I'm going to start figuring out asp.net core support, I'm hoping a middleware approach there will work nicely for that kind of setup work.

**Comment by Worthaboutapig** [comment]
I'd be happy to work on DI, I love refactoring ;) For the end user not much difference, I'd expect, except better error-handling.  But for dev, it would be much better, clear separation and dependencies, as well as a tighter design, fewer difficult-to-track bugs, I'd think.

I'm also adding in xml comments as I go with the parts I'm touching, so I'd be happy to work on that too.

I'll finish this pull request and if you think the code/ approach is ok, I'm happy to work on the DI stuff.

**Comment by Worthaboutapig** [comment]
Oh, and I was thinking of setting up a room on JabbR, I don't see one.  It's quite a good way of chatting/ throwing ideas around and helping people.  What do you think?

**Comment by Worthaboutapig** [comment]
I've just noticed 'SquishIt.Framework.Resolvers.ResolverFactory`.  Is that some sort of poor-man's DI? Hmmm. Are you familiar with it?

**Comment by AlexCuse** [comment]
Are you talking about https://jabbr.net?  I signed up there but can't see how to create a room.  Sounds like a harmless enough idea though.

Resolver factory would be about the poorest man's DI.  Its really for resource resolution - FileSystem, HTTP and 2 different types of embedded resource.  The factory just saves you from needing to reference all 4 resolver types.

**Comment by Worthaboutapig** [comment]
Yes, jabbr.net.  I've created a room and, I believe I've invited you.  I've invited some AlexCuse, anyway :).

Thanks on the factory, I guess that should be rolled into a general DI approach.  It's really a pain getting this working, as there's lots of implicit and explicit dependencies all over the place.  It's one of those things that's fine until it isn't... then it falls apart! Still, plodding through trying to minimize my impact on the rest of the codebase.

**Comment by Worthaboutapig** [comment]
I factored out all the System.Web references, but the knock-on effect for the Configuration.Instance means I may as well do the DI work too, as you suggested.  I've done a portion of it, but it'll take a day or two.  I'll try to sort it out this week.

**Comment by AlexCuse** [comment]
Anything new on this?  I just got back from a few days vacation and don't see the jabbr room anymore.  Email me if thats easier :)

**Comment by Worthaboutapig** [comment]
Hi, oh, I don't know about that, I haven't done anything :)  Either with jabbr, or with the code, been rather busy.  I can probably take a look at it in the next week or so.  Mainly I need to pull out the rest of the dependencies, which is tedious, more than difficult.

**Comment by AlexCuse** [comment]
If you want to make sure the Asp.net stuff is all removed and then lay out your gameplan for configuration stuff I can do it.  I really need to get 1.0 out soon, people are reporting more and more javascript minifier bugs that I think will be fixed by moving to the newer versions of ajaxmin/yui.

Punting on it is also an option - the configuration stuff we have now isn't ideal, but we do have it.

**Comment by Worthaboutapig** [comment]
Hi, well I can work on it today, so I'll take a look and get back to you later :)  It's quite a big change, so would make sense to include in a full version change and, personally I think it would make future development easier, though that maybe a matter of style/opinion.

**Comment by Worthaboutapig** [comment]
Hello, sorry, didn't do much before, I'm working on it now.

**Comment by AlexCuse** [comment]
Thanks, no rush - let me know if I can do anything to help.

**Comment by Worthaboutapig** [comment]
Hi, I've done some more work today.  All the configuration instance static stuff is gone, which also means the test scopes have gone (as they are just there to attempt to manage the static-ness of configuration), so everything's constructor injected now, which reveals there are a lot of dependencies for the BundleBase.  I've tidied one of these, the rile resolver stuff, which I've rewritten to actually follow the interfaces and be injected normally, which has allowed those interfaces to be grouped.  When it's working, it'll probably be worth trying to group more of the interfaces together, in order to make the injection more manageable.
The tests in SquishIt.Tests are passing (I've had to update some of them), now I need to get the versions of the tests specific to ASP.NET / Nancy to run.  Not difficult, but will take some more time.  I may get it done today... will let you know.

**Comment by Worthaboutapig** [comment]
Hi, still working on this when I can, but difficult ATM time-wise.  I'm trying to get closer to sending another PR for review, by just making the ASP.NET tests run with the new approach and add in the Nancy ones afterwards.  I need to find the time to revise all the tests, have done some of them- there's a lot of cleanup/ simplification.

**Comment by AlexCuse** [comment]
THanks - I was just thinking this morning I should reach out and see how this is going.

Anything I can help with?

**Comment by Worthaboutapig** [comment]
Well, I could try and get some more done in the next few days and push it to you, so you can take a look- after all, I'm a bit concerned that you may not like the approach I've taken and I'll have wasted loads of work! :) (Though, IMHO it's the best approach and I've thought a lot about it).

**Comment by AlexCuse** [comment]
Honestly anything is probably better than whats there now.  I'd mostly like to get started on an explainer document for people migrating from previous versions.  I also need to start thinking on how to update https://github.com/AlexCuse/SquishIt.S3

Got an example you can just drop in here in case you don't want to push?

**Comment by Worthaboutapig** [comment]
Hi, I've opened a new pull request with the latest working copy and have annotated it with a changelog, so please take a look...

**Pull request closed without merging**
